swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1/{profileId}
schemes:
  - http
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Retrieve Current Month Transactions
      description: API for fetching all transactions of the current month.
      parameters:
        - in: query
          name: month
          type: string
          required: false
          description: Optional month parameter to fetch transactions for a specific month.
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction Details
      description: API for fetching details of a specific transaction by ID.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: The ID of the transaction to retrieve details.
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update Transaction
      description: API for updating information about a specific transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: The ID of the transaction to update.
        - in: body
          name: body
          description: Transaction data to update
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
        '400':
          description: Invalid fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Delete Transaction
      description: API for removing a specific transaction by its ID.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: The ID of the transaction to delete.
      produces:
        - application/json
      responses:
        '200':
          description: Transaction deleted successfully
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        format: date
        description: Transaction date in ISO format
      type:
        type: string
        description: Type of transaction (e.g., payments)
      category:
        type: string
        description: Category of the transaction (e.g., shopping, food)
      amount:
        type: number
        format: float
        description: Amount of the transaction
      description:
        type: string
        description: Description of the transaction

  TransactionUpdate:
    type: object
    properties:
      date:
        type: string
        format: date
        description: Transaction date in ISO format
      type:
        type: string
        description: Type of transaction (e.g., expense, income)
      category:
        type: string
        description: Category of the transaction (e.g., groceries, salary)
      amount:
        type: number
        format: float
        description: Amount of the transaction
      description:
        type: string
        description: Description of the transaction

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
